config/routes.rb
Rails.application.routes.draw do

mount Tweet::Engine, at: "/tweet", as: "tweet"

=begin
  resource :user do
    member do
      get '/user/login', :to => 'user#login'
      get '/user/profile', :to => 'user#profile'
      get 'user/logout', :to => 'user#logout'
      get '/user/sign_up', :to => 'user#sign_up'
      get '/user/edit_profile', :to => 'user#edit_profile'
      get '/user/change_password', :to => 'user#change_password'
      get '/user/change_name', :to => 'user#change_name'
      get '/user/all_users', :to => 'user#all_users'
    end
  end
=end

=begin
match '/user/login', :to => 'user#login'
match '/user/profile', :to => 'user#profile'
match '/user/logout', :to => 'user#logout'
match '/user/sign_up', :to => 'user#sign_up'
match '/user/edit_profile', :to => 'user#edit_profile'
match '/user/change_password', :to => 'user#change_password'
match '/user/change_name', :to => 'user#change_name'
match '/user/all_users', :to => 'user#all_users'

namespace :tweet do
  resources :tweet
=end

  root to: "user#new"

  resources :user do
    post "new"
    get "change_name", to: "user#change_name"
    get "change_password", to: "user#change_password"
    put "change_name"
    put "change_password"
  end

=begin
  resource :user do
    member do
      get 'user/login', :to => 'user#login'
      get 'user/home', :to => 'users#home'
      get 'user/logout', :to => 'user#logout'
      get 'user/sign_up', :to => 'user#sign_up'
      get 'user/view_followers', do :view_followers
      end
    end
=end

end

app/models/user.rb
class User < ActiveRecord::Base

  attr_accessible :username, :password, :name


  #has_many :followers, foreign_key: :following_id, class_name: 'Follow'#, inverse_of: :followed_user#, source: :follow
  #has_many :followees, foreign_key: :follower_id, class_name: 'Follow', source_type: "User"#, inverse_of: :followee_user#, source: :follow

  #has_many :follows
  #has_many :followers, :through => :follows, :source => :following
  #has_many :followees, :through => :follows, source: :user, foreign_key: :user_id




  has_many :follower_association, foreign_key: :following_id, class_name: 'Tweet::Follow'
  has_many :followers, through: :follower_association, source: :follower

  has_many :following_association, foreign_key: :follower_id, class_name: 'Tweet::Follow'
  has_many :followees, through: :following_association, source: :following

  has_many :tweet_tweets, foreign_key: :user_id, class_name: 'Tweet::Tweet', dependent: :destroy
  has_many :tweet_tweets_all, through: :tweet_tweets, source: :user

  #has_many :follows, foreign_key: 'user_id', dependent: :destroy
  #has_many :following_users, through: :follows, source: :following
  #has_many :follows, foreign_key: 'user_id', dependent: :destroy

  validates_presence_of :name, :username, :password
  validates_length_of :name, :maximum => 50
  validates_length_of :username, :maximum => 40
  validates_length_of :password, :minimum => 5, :maximum => 80
  validates_uniqueness_of :username
  validates_format_of :username, :with => /^[a-z][a-z0-9]*$/i, :message => "is invalid (only lowercase alphabets and numerals characters allowed)"
  validates_format_of :password, :with => /^[A-Za-z.$@&*!][A-Za-z0-9.$@&*!]*$/i, :message => "is invalid (only alphanumeric characters, $, @, *, ! and . allowed; first character must not be number)"


=begin
  def following?(other_user)
    follows.find_by_following_id(other_user.id)
  end

  def follow!(followed_user)
    follows.create!(following_id: followed_user.id)
  end

  def following_all
    follows.find_all_by_user_id(self.id)
  end

  def unfollow!(other_user)
    follows.find_by_following_id(other_user.id).destroy
  end

=begin
  def follower(follower_id=nil)
    @follower=follower_id
  end

  def followee(followee_id=nil)
    @followee=followee_id
  end

  before_save :check_follower, :check_followee

  def check_follower
    if @follower
      self.follow.create(@follower,self.id)
    end
  end

  def check_followee
    if @flwee
      Follow.create(self.id,@flwee)
    end
  end
=end
end

app/controllers/user_controller.rb
class UserController < ApplicationController

  before_filter :authenticate

  before_filter :drop_back_home, only: [:new, :create]

  skip_before_filter :authenticate, only: [:new,:create]

  def new
    @title = "Welcome"
    if params[:submit]
      @user = User.where(username: params[:username], password: params[:password]).first
      if not @user.blank?
        session[:user_id]=@user.id
        redirect_to tweet.tweet_index_path and return
      end
      @error=true;
    end
  end

  def create
    @title = "Welcome"
    if params[:commit]
      if params[:password].to_s==params[:re_password]
        @user=User.new(:name => params[:name], :username => params[:username], :password => params[:password])
        @user.save
        if !@user.errors.blank?
          @messages = @user.errors.full_messages
          render template: "user/new"
        else
          session[:user_id] = User.where(username: params[:username]).first.id
          redirect_to tweet.tweet_index_path and return
        end
      else
        @message = 'New Passwords dont match'
        render template: "user/new"
      end
    end
  end

  def show
    if params[:id] && is_integer?(params[:id]) && User.exists?(id: params[:id])
      @userpro = User.find(params[:id])
      @user = current_user
      if params[:per_page] && is_integer?(params[:per_page]) && params[:per_page].to_i>15
        per_page = params[:per_page]
      else
        per_page = 15
      end
      if params[:page] && is_integer?(params[:page]) && params[:page].to_i>0
        page = params[:page]
      else
        page = 1
      end
      @tweets = Tweet::Tweet.where(user_id: @userpro.id).paginate(per_page: per_page, page: page, order: 'created_at DESC')
      @followers = @userpro.followers.order("created_at ASC").limit(5)
      @no_of_followers = @userpro.followers.size
      @followees = @userpro.followees.order("created_at DESC").limit(5)
      @no_of_followees = @userpro.followees.size
      @title = "#{@userpro.name}'s Profile"
    else
      redirect_to tweet.tweet_index_path and return
    end
  end

  def destroy
    if params[:logout]
      session.delete(:user_id)
      @title = "See you soon"
    else
      redirect_to tweet.tweet_index_path and return
    end
  end

  def edit
    @user = current_user
    @title = "Your Profile"
  end

  def change_password
    if params[:back]
      redirect_to edit_user_path(session[:user_id])
    end
    @user = current_user
    @title = "Your Profile"
    if params[:commit]
      if(params[:new_password].to_s==params[:re_password].to_s)
        if params[:old_password].to_s==@user.password.to_s
          @user.password = params[:new_password]
          @user.save
          if @user.errors.full_messages.size>0
            session[:messages] = @user.errors.full_messages
          else
            @message='<span style="color:green">Password successfully changed</span>'.html_safe
          end
        else
          @message='Invalid Password'
        end
      else
        @message='New Passwords dont match'
      end
    end
  end

  def change_name
    if params[:back]
      redirect_to edit_user_path(session[:user_id])
    end
    @user = current_user
    @title = "Your Profile"
    if params[:commit]
        if params[:name]
          @user.name = params[:name]
          @user.save
          if @user.errors.full_messages.size>0
            session[:messages] = @user.errors.full_messages
          end
          @message='<span style="color:green">Name successfully changed</span>'.html_safe
        end
    end
  end


  def index
    @title = "All Users"
    @user = current_user
    if params[:per_page] && is_integer?(params[:per_page]) && params[:per_page].to_i>15
      per_page = params[:per_page]
    else
      per_page = 10
    end
    if params[:page] && is_integer?(params[:page]) && params[:page].to_i>0
      page = params[:page]
    else
      page = 1
    end
    @users = User.where(User.arel_table[:id].not_eq(session[:user_id])).paginate(per_page: per_page, page: page, order: 'name')
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/user/all_users.html.erb
<div id="page">

  <div id="users_all">
    <% if @users.size>0 %>
        <h3>&nbsp;All users</h3>
        <table border="0" >
        <% @users.each do |u| %>
           <tr>
             <td>
               <% if @user.followees.exists?(u)%>
                   <%= form_tag "/tweet/follow/delete", method: :put do %>
                   <% if params[:page] %>
                     <% page = params[:page] %>
                   <% else %>
                     <% page = 1 %>
                   <% end %>
                   <% if params[:per_page] %>
                     <% per_page = params[:per_page] %>
                   <% else %>
                     <% per_page = 10 %>
                   <% end %>
                   <%= hidden_field_tag :following_id,"#{u.id}" %>
                   <%= hidden_field_tag :redirect_url, "/user/all_users?per_page=#{per_page}&page=#{page}" %>
                   <%= submit_tag "Unfollow", id: :submit %>
                   <% end %>
               <% else %>
                 <%= form_tag "/tweet/follow/create", method: :put do %>
                       <% if params[:page] %>
                           <% page = params[:page] %>
                       <% else %>
                           <% page = 1 %>
                       <% end %>
                       <% if params[:per_page] %>
                           <% per_page = params[:per_page] %>
                       <% else %>
                           <% per_page = 10 %>
                       <% end %>
                   <%= hidden_field_tag :following_id,"#{u.id}" %>
                   <%= hidden_field_tag :redirect_url, "/user/all_users?per_page=#{per_page}&page=#{page}" %>
                   <%= submit_tag "Follow", id: :submit %>
                 <% end %>
               <% end %>
             </td>
             <td>
               <%= link_to u.name, controller: :user, action: :profile, user: u.id %>
             </td>
           </tr>
       <% end %>
        </table>
        <br/>
        <%= will_paginate @users %>
        <%  else %>
        <h3>No other user.</h3>
    <% end %>

  </div>

</div>

</div>
<div id="footer">

</div>

app/views/user/change_name.html.erb
<div id="page">

  <p><b>Change Your Name</b></p>
  <% if session[:messages] %>
      Errors in form data:
      <ul>
        <% session[:messages].each do |message| %>
            <li><div id="form_error" style="color: red;"><%= message %></div></li>
        <% end %>
      </ul>
      <% session.delete(:messages)%>
  <% end %>
  <% if @message %>
      <div id="form_error" style="color: red;"><%= @message %></div>
  <% end %>
  <div id="change_name_form">
  <%= form_tag user_change_name_path, method: :put do %>
      <table border="0">
        <tr>
          <td align="right">
            <label for="name">New Name: </label>
          </td>
          <td>
            <%= text_field_tag :name, @user.name, :maxlength => 50  %>
          </td>
        <tr>
      </table>
      <%= submit_tag "Submit", id: :submit %>&nbsp;&nbsp;<%= submit_tag "Back", name: :back, id: :submit %>
  <% end %>
  </div>
</div>

app/views/user/change_password.html.erb
<div id="page">

    <p><b>Change Password</b></p>

    <% if session[:messages] %>
    Errors in form data:
    <ul>
        <% session[:messages].each do |message| %>
        <li><div id="form_error" style="color: red;"><%= message %></div></li>
        <% end %>
    </ul>
    <% session.delete(:messages)%>
    <% end %>

    <% if @message %>
    <div style="color: red;"><%= @message %></div>
    <% end %>

    <div id="change_password_form">
        <%= form_tag user_change_password_path, method: :put do %>
            <table border="0">
                <tr>
                    <td align="right">
                        <label for="old_password">Old Password: </label>
                    </td>
                    <td>
                        <%= password_field_tag :old_password %>
                    </td>
                <tr>
                <tr>
                    <td align="right">
                        <label for="new_password">New Password: </label>
                    </td>
                    <td>
                        <%= password_field_tag :new_password %>
                    </td>
                <tr>
                <tr>
                    <td align="right">
                        <label for="re_password">Retype Password: </label>
                    </td>
                    <td>
                        <%= password_field_tag :re_password %>
                    </td>
                <tr>
            </table>
            <%= submit_tag "Submit", id: :submit  %>&nbsp;&nbsp;<%= submit_tag "Back", name: :back, id: :submit %>
        <% end %>
    </div>

</div>

app/views/user/destroy.html.erb
<div id="page">

  <p>You have been successfully logged out!</p>
  <%= link_to 'Back', new_user_path %>

</div>

app/views/user/edit.html.erb
<div id="page">
  <p><b>Profile</b></p>
  <% if @message %>
      <div id="form_error" style="color: red;"><%= @message %></div>
  <% end %>
  Name:&nbsp;<%= @user.name %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= link_to 'Edit', user_change_name_path(session[:user_id]) %>
  <br/>
  <br/>
  <br/>
  <%= link_to 'Change&nbsp;Password'.html_safe, user_change_password_path(session[:user_id]) %>
</div>

app/views/user/edit_profile.html.erb
<div id="page">
  <p><b>Profile</b></p>
  <% if @message %>
      <div id="form_error" style="color: red;"><%= @message %></div>
  <% end %>
  Name:&nbsp;<%= @user.name %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= link_to 'Edit', controller: :user, :action => 'change_name' %>
  <br/>
  <br/>
  <br/>
  <%= link_to 'Change&nbsp;Password'.html_safe, controller: :user, :action => 'change_password' %>
</div>

app/views/user/index.html.erb
<div id="page">

  <div id="users_all">
    <% if @users.size>0 %>
        <h3>&nbsp;All users</h3>
        <table border="0" >
        <% @users.each do |u| %>
           <tr>
             <td>
               <% if @user.followees.exists?(u)%>
                   <%= form_tag tweet.follow_path(session[:user_id]), method: :delete do %>
                   <% if params[:page] %>
                     <% page = params[:page] %>
                   <% else %>
                     <% page = 1 %>
                   <% end %>
                   <% if params[:per_page] %>
                     <% per_page = params[:per_page] %>
                   <% else %>
                     <% per_page = 10 %>
                   <% end %>
                   <%= hidden_field_tag :following_id,"#{u.id}" %>
                   <%= hidden_field_tag :redirect_url, user_index_path %>
                   <%= submit_tag "Unfollow", id: :submit %>
                   <% end %>
               <% else %>
                 <%= form_tag tweet.follow_index_path, method: :post do %>
                       <% if params[:page] %>
                           <% page = params[:page] %>
                       <% else %>
                           <% page = 1 %>
                       <% end %>
                       <% if params[:per_page] %>
                           <% per_page = params[:per_page] %>
                       <% else %>
                           <% per_page = 10 %>
                       <% end %>
                   <%= hidden_field_tag :following_id,"#{u.id}" %>
                   <%= hidden_field_tag :redirect_url, user_index_path %>
                   <%= submit_tag "Follow", id: :submit %>
                 <% end %>
               <% end %>
             </td>
             <td>
               <%= link_to u.name, user_path(u.id) %>
             </td>
           </tr>
       <% end %>
        </table>
        <br/>
        <%= will_paginate @users %>
        <%  else %>
        <h3>No other user.</h3>
    <% end %>

  </div>

</div>

</div>
<div id="footer">

</div>

app/views/user/login.html.erb
<div id="page">

  <div id="login_form">

    <div id="head">
      LOGIN
    </div>
    <div id="rest">
        <% if @error %>
            <div id="form_error" style="color: red;">Username and Password do not match or exist!</div>
        <% end %>

      <%= form_tag "/user/login", autocomplete: :off do %>

        <table border="0">

            <tr>
              <td>
                <label for="username">Username</label>
              </td>
            </tr>
            <tr>
              <td>
                <input id="username" name="username" type="text" maxlength="40" value="" />
              </td>
            </tr>

            <tr>
              <td>
                <label for="password">Password</label>
              </td>
            </tr>
            <tr>
              <td>
                <input id="password" name="password" type="password" maxlength="80" value=""/>
              </td>
            </tr>

        </table>

        <input type="submit" class="submit" name="submit" value="Login" OnClick="this.disable()">

      <% end %>
    </div>
  </div>

  <div id="sign_up_form">
    <div id="head">
      NEW&nbsp;HERE?&nbsp;SIGN&nbsp;UP
    </div>
    <div id="rest">
      <% if !@messages.blank? %>
          Errors in form data:
          <ul>
            <% @messages.each do |message| %>
                <li><div id="form_error" style="color: red;"><%= message %></div></li>
            <% end %>
          </ul>
      <% end %>

      <% if @message %>
          <div id="form_error" style="color: red;"><%= @message %></div>
      <% end %>

      <%= form_tag '/user/sign_up', autocomplete: :off do %>
          <table border="0">
            <tr>
              <td>
                <label for="name">Full Name: </label>
              </td>
            </tr>
            <tr>
              <td>
                <%= text_field_tag :name %>
              </td>
            </tr>
            <tr>
              <td>
                <label for="username">Username: </label>
              </td>
            </tr>
            <tr>
              <td>
                <%= text_field_tag :username %>
              </td>
            </tr>
            <tr>
              <td>
                <label for="password">Password: </label>
              </td>
            </tr>
            <tr>
              <td>
                <%= password_field_tag :password %>
              </td>
            </tr>
            <tr>
              <td>
                <label for="re_password">Retype Password: </label>
              </td>
            </tr>
            <tr>
              <td>
                <%= password_field_tag :re_password %>
              </td>
            </tr>
          </table>
          <%= submit_tag "Sign Up", :name => "submit", :class => "submit" %>
      <% end %>
     </div>
  </div>

</div>

app/views/user/logout.html.erb
<div id="page">

  <p>You have been successfully logged out!</p>
  <%= link_to 'Back', controller: 'user', action: 'login' %>

</div>

app/views/user/new.html.erb
<div id="page">

  <div id="login_form">

    <div id="head">
      LOGIN
    </div>
    <div id="rest">
        <% if @error %>
            <div id="form_error" style="color: red;">Username and Password do not match or exist!</div>
        <% end %>

      <%= form_tag post_new_user, autocomplete: :off do %>

        <table border="0">

            <tr>
              <td>
                <label for="username">Username</label>
              </td>
            </tr>
            <tr>
              <td>
                <input id="username" name="username" type="text" maxlength="40" value="" />
              </td>
            </tr>

            <tr>
              <td>
                <label for="password">Password</label>
              </td>
            </tr>
            <tr>
              <td>
                <input id="password" name="password" type="password" maxlength="80" value=""/>
              </td>
            </tr>

        </table>

        <input type="submit" class="submit" name="submit" value="Login" OnClick="this.disable()">

      <% end %>
    </div>
  </div>

  <div id="sign_up_form">
    <div id="head">
      NEW&nbsp;HERE?&nbsp;SIGN&nbsp;UP
    </div>
    <div id="rest">
      <% if !@messages.blank? %>
          <ul>
            <% @messages.each do |message| %>
                <li><div id="form_error" style="color: red;"><%= message %></div></li>
            <% end %>
          </ul>
      <% end %>

      <% if @message %>
          <div id="form_error" style="color: red;"><%= @message %></div>
      <% end %>

      <%= form_tag user_new_path(1), autocomplete: :off do %>
          <table border="0">
            <tr>
              <td>
                <label for="name">Full Name: </label>
              </td>
            </tr>
            <tr>
              <td>
                <%= text_field_tag :name %>
              </td>
            </tr>
            <tr>
              <td>
                <label for="username">Username: </label>
              </td>
            </tr>
            <tr>
              <td>
                <%= text_field_tag :username %>
              </td>
            </tr>
            <tr>
              <td>
                <label for="password">Password: </label>
              </td>
            </tr>
            <tr>
              <td>
                <%= password_field_tag :password %>
              </td>
            </tr>
            <tr>
              <td>
                <label for="re_password">Retype Password: </label>
              </td>
            </tr>
            <tr>
              <td>
                <%= password_field_tag :re_password %>
              </td>
            </tr>
          </table>
          <%= submit_tag "Sign Up", :class => "submit" %>
      <% end %>
     </div>
  </div>

</div>

app/views/user/profile.html.erb
<div id="page">

  <div id="tweets">

    <div id="tweet_head">
      <%= @userpro.name %>'s Latest Tweets
    </div>

    <% if @tweets.size>0
         @tweets.each do |t|
    %>
            <div id="tweet">

              <div id="user"><span class="username"><%= t.name %></span> <span id="time"><%= t.created_at.in_time_zone('New Delhi').day %>/<%= t.created_at.in_time_zone('New Delhi').month %>/<%= t.created_at.in_time_zone('New Delhi').year %>&nbsp;<%= t.created_at.in_time_zone('New Delhi').hour %>:<%= t.created_at.in_time_zone('New Delhi').min %>:<%= t.created_at.in_time_zone('New Delhi').sec %>&nbsp;</span></div>
              <div id="message"><%= t.message %></div>

            </div>
        <% end %>
            <%= will_paginate @tweets %>
        <% else %>
        <div id="tweet">
          No tweets to display! :(
        </div>
    <%
       end
    %>
    <br/><br/>
  </div>

  <div id="otherusers">

    <div id="followers">
      <% if @followers.size>0 %>
          <div id="head"><%= @userpro.name %>'s followers</div>
          <% @followers.each do |f| %>

              <div id="follower">
                <%= f.name %>
              </div>

          <% end %>
          <% if @no_of_followers>5 %>

              <%= link_to 'view all >>', controller: :user, :action => 'view_followers', :page_id => 1 %>

          <% end
             else %>
          <div id="head"><%= @userpro.name %>'s has no followers.</div>
      <% end %>
    </div>

    <div id="followees">
      <% if @followees.size>0 %>
          <div id="head">People <%= @userpro.name %> follows</div>
          <% @followees.each do |f| %>

              <div id="followee">
                <%= f.name %>
              </div>


          <% end %>
          <% if @no_of_followees>5 %>
              <%= link_to 'view all >>', controller: :user, :action => 'view_followees', :page_id => 1 %>
          <% end
             else %>
          <div id="head"><%= @userpro.name %> does not follow anyone.</div>
      <% end %>
    </div>
    <% if @user.followees.exists?(@userpro)%>
        <%= form_tag "/tweet/follow/delete", method: :put do %>
            <% if params[:page] %>
                <%= hidden_field_tag :page, "#{params[:page]}" %>
            <% else %>
                <%= hidden_field_tag :page, "1" %>
            <% end %>
            <% if params[:per_page] %>
                <%= hidden_field_tag :per_page, "#{params[:per_page]}" %>
            <% else %>
                <%= hidden_field_tag :per_page, "3" %>
            <% end %>
            <%= hidden_field_tag :redirect_url, "/user/profile?user=#{@userpro.id}"%>
            <%= hidden_field_tag :following_id,"#{@userpro.id}" %>
            <%= submit_tag "Unfollow", class: :submit %>
        <% end %>
    <% else %>
        <%= form_tag "/tweet/follow/create", method: :put do %>
            <% if params[:page] %>
                <%= hidden_field_tag :page, "#{params[:page]}" %>
            <% else %>
                <%= hidden_field_tag :page, "1" %>
            <% end %>
            <% if params[:per_page] %>
                <%= hidden_field_tag :per_page, "#{params[:per_page]}" %>
            <% else %>
                <%= hidden_field_tag :per_page, "3" %>
            <% end %>
            <%= hidden_field_tag :redirect_url, "/user/profile?user=#{@userpro.id}"%>
            <%= hidden_field_tag :following_id,"#{@userpro.id}" %>
            <%= submit_tag "Follow", class: :submit %>
        <% end %>
    <% end %>
  </div>
</div>

app/views/user/show.html.erb
<div id="page">

  <div id="tweets">

    <div id="tweet_head">
      <%= @userpro.name %>'s Latest Tweets
    </div>

    <% if @tweets.size>0
         @tweets.each do |t|
    %>
            <div id="tweet">

              <div id="user"><span class="username"><%= t.name %></span> <span id="time"><%= t.created_at.in_time_zone('New Delhi').day %>/<%= t.created_at.in_time_zone('New Delhi').month %>/<%= t.created_at.in_time_zone('New Delhi').year %>&nbsp;<%= t.created_at.in_time_zone('New Delhi').hour %>:<%= t.created_at.in_time_zone('New Delhi').min %>:<%= t.created_at.in_time_zone('New Delhi').sec %>&nbsp;</span></div>
              <div id="message"><%= t.message %></div>

            </div>
        <% end %>
            <%= will_paginate @tweets %>
        <% else %>
        <div id="tweet">
          No tweets to display! :(
        </div>
    <%
       end
    %>
    <br/><br/>
  </div>

  <div id="otherusers">

    <div id="followers">
      <% if @followers.size>0 %>
          <div id="head"><%= @userpro.name %>'s followers</div>
          <% @followers.each do |f| %>

              <div id="follower">
                <%= f.name %>
              </div>

          <% end %>
          <% if @no_of_followers>5 %>

              <%= link_to 'view all >>', controller: :user, :action => 'view_followers', :page_id => 1 %>

          <% end
             else %>
          <div id="head"><%= @userpro.name %>'s has no followers.</div>
      <% end %>
    </div>

    <div id="followees">
      <% if @followees.size>0 %>
          <div id="head">People <%= @userpro.name %> follows</div>
          <% @followees.each do |f| %>

              <div id="followee">
                <%= f.name %>
              </div>


          <% end %>
          <% if @no_of_followees>5 %>
              <%= link_to 'view all >>', controller: :user, :action => 'view_followees', :page_id => 1 %>
          <% end
             else %>
          <div id="head"><%= @userpro.name %> does not follow anyone.</div>
      <% end %>
    </div>
    <% if @user.followees.exists?(@userpro)%>
        <%= form_tag tweet.follow_path(session[:user_id]), method: :delete do %>
            <% if params[:page] %>
                <%= hidden_field_tag :page, "#{params[:page]}" %>
            <% else %>
                <%= hidden_field_tag :page, "1" %>
            <% end %>
            <% if params[:per_page] %>
                <%= hidden_field_tag :per_page, "#{params[:per_page]}" %>
            <% else %>
                <%= hidden_field_tag :per_page, "3" %>
            <% end %>
            <%= hidden_field_tag :redirect_url, user_path(@userpro.id) %>
            <%= hidden_field_tag :following_id,"#{@userpro.id}" %>
            <%= submit_tag "Unfollow", class: :submit %>
        <% end %>
    <% else %>
        <%= form_tag tweet.follow_index_path, method: :post do %>
            <% if params[:page] %>
                <%= hidden_field_tag :page, "#{params[:page]}" %>
            <% else %>
                <%= hidden_field_tag :page, "1" %>
            <% end %>
            <% if params[:per_page] %>
                <%= hidden_field_tag :per_page, "#{params[:per_page]}" %>
            <% else %>
                <%= hidden_field_tag :per_page, "3" %>
            <% end %>
            <%= hidden_field_tag :redirect_url, user_path(@userpro.id) %>
            <%= hidden_field_tag :following_id,"#{@userpro.id}" %>
            <%= submit_tag "Follow", class: :submit %>
        <% end %>
    <% end %>
  </div>
</div>

app/views/user/sign_up.html.erb
<!DOCTYPE html>
<html>
<head>
<title></title>
<style type="text/css" media="screen">
</style>
</head>
<body>

<div id="page">

  <p><b>Sign Up</b></p>
  <% if !@messages.blank? %>
      Errors in form data:
      <ul>
        <% @messages.each do |message| %>
          <li><div id="form_error" style="color: red;"><%= message %></div></li>
        <% end %>
      </ul>
  <% end %>

    <% if @message %>
        <div id="form_error" style="color: red;"><%= @message %></div>
    <% end %>

  <%= form_tag :controller => :user, :action => 'sign_up' do %>
      <table border="0">
        <tr>
          <td align="right">
            <label for="name">Full Name: </label>
          </td>
          <td>
            <%= text_field_tag :name %>
          </td>
        <tr>
        <tr>
          <td align="right">
            <label for="username">Username: </label>
          </td>
          <td>
            <%= text_field_tag :username %>
          </td>
        <tr>
        <tr>
          <td align="right">
            <label for="password">Password: </label>
          </td>
          <td>
            <%= password_field_tag :password %>
          </td>
        <tr>
        <tr>
          <td align="right">
            <label for="re_password">Retype Password: </label>
          </td>
          <td>
            <%= password_field_tag :re_password %>
          </td>
        <tr>
      </table>
      <%= submit_tag("Submit") %>&nbsp;&nbsp;<%= submit_tag "Back", name: :back %>
  <% end %>

</div>
<div id="footer">

</div>
</body>
</html>