config/routes.rb
Rails.application.routes.draw do

mount Tweet::Engine, at: "/tweet", as: "tweet"

=begin
  resource :user do
    member do
      get '/user/login', :to => 'user#login'
      get '/user/profile', :to => 'user#profile'
      get 'user/logout', :to => 'user#logout'
      get '/user/sign_up', :to => 'user#sign_up'
      get '/user/edit_profile', :to => 'user#edit_profile'
      get '/user/change_password', :to => 'user#change_password'
      get '/user/change_name', :to => 'user#change_name'
      get '/user/all_users', :to => 'user#all_users'
    end
  end
=end

=begin
match '/user/login', :to => 'user#login'
match '/user/profile', :to => 'user#profile'
match '/user/logout', :to => 'user#logout'
match '/user/sign_up', :to => 'user#sign_up'
match '/user/edit_profile', :to => 'user#edit_profile'
match '/user/change_password', :to => 'user#change_password'
match '/user/change_name', :to => 'user#change_name'
match '/user/all_users', :to => 'user#all_users'

namespace :tweet do
  resources :tweet
=end

  root to: "user#new"

  resources :user do
    post "new"
    get "change_name", to: "user#change_name"
    get "change_password", to: "user#change_password"
    put "change_name"
    put "change_password"
  end

=begin
  resource :user do
    member do
      get 'user/login', :to => 'user#login'
      get 'user/home', :to => 'users#home'
      get 'user/logout', :to => 'user#logout'
      get 'user/sign_up', :to => 'user#sign_up'
      get 'user/view_followers', do :view_followers
      end
    end
=end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @title %></title>
  <%= favicon_link_tag "avengers.ico" %>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
    <body>
        <div id="top">
          <div id="topbar">

              <% if session[:user_id] %>
                <div id="welcome">
                 Welcome <%= @user.name %>!&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href='<%= tweet.tweet_index_path %>' >Home</a> | <a href='<%= edit_user_path(session[:user_id]) %>' >Edit Profile</a> | <a href='<%= user_index_path %>' >All Users</a>
                </div>
                <div id="logout">
                  <%= form_tag logout_user, method: :delete do %>
                    <%= submit_tag "Logout", :name => :logout, :class => :submit %>
                  <% end %>
                </div>
              <% else %>
                <div id="welcome">
                  Welcome!
                </div>
              <% end %>
          </div>
        </div>

        <%= yield %>

        <div id="footer">
          Copyright &copy; localhost 2013. All Rights Reserved.
        </div>

    </body>
</html>